"""Issue #157: the engine compares and orders text in the model's collation.

It compared text by code point after case-folding: "_x" < "1x" was FALSE,
"Ölund" < "Zeta" FALSE, and MIN / MAX / FIRSTNONBLANK / LASTNONBLANK and
CONCATENATEX's ordering followed the code points. Desktop compares as
Windows' NLS sorting does for the model's locale, at the version of its sort
tables (pbix_mcp.dax.collation): case-insensitively, an accent after its
letter, punctuation before the digits, hyphens and apostrophes weighing only
where nothing else tells two texts apart (at the end of a text, more than an
accent); "æ" = "ae", "ß" = "ss", "²" = "2".

Expected values: Power BI Desktop 2.152 over ADOMD (build_b156.py,
build_b157.py, build_b157d.py, build_b157g.py and the pair probes of
build_b157e)."""
from __future__ import annotations

import pytest

from pbix_mcp.dax import collation
from pbix_mcp.dax import engine as de

pytestmark = pytest.mark.unit

ORDER156 = [
    '_x',
    '1x',
    'a10',
    'a2',
    'Americas',
    'APAC',
    'apple',
    'b',
    'ba',
    'Bz',
    'eclair',
    'éclair',
    'olive',
    'Ölund',
    'Zeta',
]

ORDER157 = [
    'ẞ',
    "'",
    '-',
    ' ab',
    '!',
    '"',
    '#',
    '$',
    '%',
    '&',
    '(',
    ')',
    '*',
    ',',
    '.',
    '/',
    ':',
    ';',
    '?',
    '@',
    '[',
    '\\',
    ']',
    '^',
    '_',
    '`',
    '{',
    '|',
    '}',
    '~',
    '¡',
    '¿',
    '£',
    '¥',
    '€',
    '+',
    '<',
    '=',
    '>',
    '±',
    '«',
    '»',
    '§',
    '©',
    '®',
    '°',
    'µ',
    '¶',
    '…',
    '•',
    '001',
    '01',
    '½',
    '1',
    '①',
    '١',
    '1.0',
    '10',
    '1a',
    '2',
    '²',
    'Å',
    'å',
    'a  b',
    'a b',
    'a\tb',
    'a01',
    'a1',
    'aa',
    'ab',
    'ad',
    'ae',
    'Æ',
    'æ',
    'af',
    'Angstrom',
    'Ångström',
    'b',
    'c',
    'co op',
    'co&op',
    'co(op',
    'co,op',
    'co.op',
    'co/op',
    'co_op',
    'co’op',
    'co+op',
    'coo',
    'co-o',
    'coop',
    '-coop',
    'c-oop',
    "co'op",
    'co-op',
    'co--op',
    'co–op',
    'co—op',
    'coop-',
    'cop',
    'cote',
    'coté',
    'côte',
    'côté',
    'd',
    'ð',
    'Ð',
    'e',
    'É',
    'é',
    'È',
    'è',
    'ė',
    'ê',
    'Ê',
    'ë',
    'Ë',
    'ě',
    'ē',
    'ę',
    'éa',
    'Éa',
    'eb',
    'éb',
    'facade',
    'façade',
    'i',
    'ı',
    'İ',
    'j',
    'l',
    'Ł',
    'ł',
    'm',
    'n',
    'ñ',
    'Ñ',
    'naive',
    'naïve',
    'o',
    'ö',
    'Ö',
    'Ø',
    'ø',
    'oe',
    'œ',
    'Œ',
    'p',
    'resume',
    'resumé',
    'résumé',
    'sr',
    'ss',
    'ß',
    'st',
    'þ',
    'Þ',
    'th',
    '™',
    'u',
    'ü',
    'Ü',
    'v',
    'w',
    'x',
    'y',
    'z',
    'Zuerich',
    'Zurich',
    'Zürich',
    'α',
    'β',
    'ω',
    'Ω',
    'а',
    'б',
    'Я',
    'я',
    'ｱ',
    'ア',
    'あ',
    '😀',
    '가',
    '中',
    '日',
]

ORDER157G = [
    '-a-',
    'a-',
    'a b',
    'a b-',
    'a!',
    'a-!',
    'a!-',
    'a.b',
    'a.b-',
    'a1',
    'a-1',
    'a1-',
    'ab',
    '-ab',
    'a-b',
    'a--b',
    '-ab-',
    "a'b'",
    "a'b-",
    'a--b-',
    "a-b'",
    'a-b-',
    'a-b–',
    'a–b–',
    "ab'",
    'ab-',
    'ab–',
    'ab--',
    'abc',
    'a-bc',
    'a-b-c',
    'ab-c',
    'a-b-c-',
    'a-bc-',
    'ab-c-',
    "abc'",
    'abc-',
    'abd',
    'ab-d',
    'a-bx',
    'ab-x',
    'ae',
    'a-e',
    'aé',
    'a-é',
    'ae-',
    'aé-',
    'co-o',
    'co-o-',
    'coop',
    'co-op',
    'co-op-',
    'coop-',
    'cop',
]

# (a, b, Desktop: a < b, Desktop: a = b)
PAIRS = [
    ('_x', '1x', 1, 0),
    ('co-op', 'coop', 0, 0),
    ('co-op', 'cop', 1, 0),
    ("co'op", 'coop', 0, 0),
    ('co op', 'coop', 1, 0),
    ('é', 'e', 0, 0),
    ('é', 'f', 1, 0),
    ('É', 'é', 0, 1),
    ('æ', 'ae', 0, 1),
    ('æ', 'af', 1, 0),
    ('ß', 'ss', 0, 1),
    ('ß', 'st', 1, 0),
    ('ø', 'o', 0, 0),
    ('ø', 'p', 1, 0),
    ('å', 'aa', 1, 0),
    ('å', 'b', 1, 0),
    ('a10', 'a2', 1, 0),
    ('A', 'a', 0, 1),
    ('Ö', 'ö', 0, 1),
    ('ı', 'i', 0, 0),
    ('α', 'z', 0, 0),
    ('а', 'α', 0, 0),
    ('-', '_', 1, 0),
    ('!', '-', 0, 0),
    ('€', '$', 0, 0),
    ('cote', 'côté', 1, 0),
    ('coté', 'côte', 1, 0),
    ('a b', 'ab', 1, 0),
    (' ab', 'ab', 1, 0),
    ('', 'a', 1, 0),
    ('½', '1', 1, 0),
    ('²', '2', 0, 1),
    ('²', '3', 1, 0),
    ('йа', 'іб', 0, 0),
    ('йа', 'иб', 0, 0),
    ('й', 'і', 0, 0),
    ('й', 'и', 0, 0),
    ('бой', 'боит', 0, 0),
    ('ab', 'ab ', 1, 0),
    ('ab ', 'ab', 0, 0),
    ('a', 'a  ', 1, 0),
    (' a', 'a', 1, 0),
    ('ab', 'ab\xa0', 1, 0),
    ('šs', 'ß–', 1, 0),
    ('üë', "u—É'", 1, 0),
    ('–2', '\xad²', 0, 0),
    ('–2', '²', 0, 0),
    ('ss–', 'šs', 0, 0),
    ('ss-', 'šs', 0, 0),
    ('s-s', 'šs', 1, 0),
    ('ab-', 'áb', 0, 0),
    ('a-b', 'áb', 1, 0),
    ("ab'", 'áb', 0, 0),
    ('ue', 'ü', 0, 0),
    ('u-e', 'üe', 1, 0),
    ('coop', 'co-op', 1, 0),
    ('co-op', 'côop', 1, 0),
    ('ія', 'ї', 1, 0),
    ('й', 'ї', 0, 0),
    ('e-', 'é', 0, 0),
    ('e–', 'é', 0, 0),
    ("e'", 'é', 0, 0),
]


def _model():
    rows = [{"c": v, "i": n} for n, v in enumerate(ORDER156)]
    return {"T": {"columns": ["c", "i"], "rows": [[r["c"], r["i"]] for r in rows]}}


def _eval(expr, tables=None):
    return de.evaluate_measures_smart(["p"], tables or _model(), {"p": expr}, {},
                                      simulate_row_context=False)["p"]


@pytest.mark.parametrize("name,order", [("b156", ORDER156), ("b157", ORDER157), ("b157g", ORDER157G)])
def test_desktop_sort_orders(name, order):
    keys = [collation.sort_key(s) for s in order]
    assert all(a <= b for a, b in zip(keys, keys[1:])), [
        (order[i], order[i + 1]) for i in range(len(keys) - 1) if keys[i] > keys[i + 1]]


@pytest.mark.parametrize("a,b,lt,eq", PAIRS, ids=[f"{n:02d}" for n in range(len(PAIRS))])
def test_expression_comparisons(a, b, lt, eq):
    la, lb = a.replace('"', '""'), b.replace('"', '""')
    assert _eval(f'IF("{la}" < "{lb}", 1, 0)') == lt
    assert _eval(f'IF("{la}" = "{lb}", 1, 0)') == eq


@pytest.mark.parametrize("expr,want", [
    ("MIN(T[c])", "_x"), ("MAX(T[c])", "Zeta"),
    ("FIRSTNONBLANK(T[c], 1)", "_x"), ("LASTNONBLANK(T[c], 1)", "Zeta"),
    ('CONCATENATEX(VALUES(T[c]), T[c], ",", T[c], ASC)', ",".join(ORDER156)),
    ('CALCULATE(COUNTROWS(T), T[c] > "b")', 7), ('CALCULATE(COUNTROWS(T), T[c] < "a2")', 3),
    ('COUNTROWS(FILTER(T, T[c] > "b"))', 7),
    ('CALCULATE(COUNTROWS(T), T[c] >= "Americas", T[c] <= "apple")', 3),
    ('MAXX(VALUES(T[c]), T[c])', "Zeta"), ('MIN("APAC", "apple")', "APAC"),
])
def test_text_aggregates(expr, want):
    assert _eval(expr) == want


def test_column_order_breaks_ties_by_code_point():
    assert sorted(["\u00e9", "\u00c9", "e"], key=collation.column_order_key) == ["e", "\u00c9", "\u00e9"]
    assert collation.equal("\u00e6", "ae") and not collation.equal("\u00e9", "e")
