"""Issue #118: ALLSELECTED keeps the measure's own CALCULATE filters, and puts
back the rows an iteration iterated.

Power BI Desktop 2.152 over ADOMD (build_b118.py): 30 measures under 10 query
shapes, one SUMMARIZECOLUMNS per cell, generated from Desktop's output.
  * an explicit CALCULATE filter stays inside ALLSELECTED, every form:
    CALCULATE(CALCULATE([Sales], ALLSELECTED(T)), T[Cat] = "A") is A's 40 (the
    engine answered the 75 total), and a DATEADD filter survives an inner
    ALLSELECTED(Dt);
  * a grouping goes back to the query's selection, a row transition to the
    iteration's ROWS: SUMX(FILTER(ALL(T[Cat]), T[Cat] = "A"),
    CALCULATE(COUNTROWS(ALLSELECTED(T)))) is 2, not 4;
  * the column form keeps only its own columns: CALCULATE(COUNTROWS(
    ALLSELECTED(Dt[Date])), Dt[Month] = 2) is all 91 dates;
  * FILTER's row transition puts the row in scope:
    COUNTROWS(FILTER(T, CALCULATE(IF(ISINSCOPE(T[Cat]), 1, 0)) = 1)) is 4.

Left out: f_dates_last, a FILTER condition that holds an aggregate and reads
the row's own column, which is #116.
"""
from __future__ import annotations

from datetime import datetime, timedelta

import pytest

from pbix_mcp.dax import engine as de

pytestmark = pytest.mark.unit

DAYS = [datetime(2024, 1, 1) + timedelta(days=i) for i in range(91)]
TABLES = {
    "T": {"columns": ["Region", "Cat", "Amount"],
          "rows": [["North", "A", 10.0], ["North", "B", 20.0], ["South", "A", 30.0], ["South", "B", 15.0]]},
    "D": {"columns": ["Region", "Zone"], "rows": [["North", "Z1"], ["South", "Z2"]]},
    "Dt": {"columns": ["Date", "Month"], "rows": [[d, d.month] for d in DAYS]},
    "F": {"columns": ["Date", "Amount"],
          "rows": [[d, float(i % 7 + 1)] for i, d in enumerate(DAYS) if d.month < 3 or d.day < 10]},
}
RELS = [{"FromTable": "T", "FromColumn": "Region", "ToTable": "D", "ToColumn": "Region", "IsActive": True,
         "CrossFilteringBehavior": 1, "FromCardinality": 2, "ToCardinality": 1},
        {"FromTable": "F", "FromColumn": "Date", "ToTable": "Dt", "ToColumn": "Date", "IsActive": True,
         "CrossFilteringBehavior": 1, "FromCardinality": 2, "ToCardinality": 1}]
MEASURES = {
    "Sales": "SUM(T[Amount])",
    "FS": "SUM(F[Amount])",
    "m_tab_cat": 'CALCULATE(CALCULATE([Sales], ALLSELECTED(T)), T[Cat] = "A")',
    "m_col_same": 'CALCULATE(CALCULATE([Sales], ALLSELECTED(T[Cat])), T[Cat] = "A")',
    "m_col_other": 'CALCULATE(CALCULATE([Sales], ALLSELECTED(T[Region])), T[Cat] = "A")',
    "m_noarg": 'CALCULATE(CALCULATE([Sales], ALLSELECTED()), T[Cat] = "A")',
    "m_dim_tab": 'CALCULATE(CALCULATE([Sales], ALLSELECTED(D)), D[Zone] = "Z1")',
    "m_dim_col": 'CALCULATE(CALCULATE([Sales], ALLSELECTED(D[Zone])), D[Zone] = "Z1")',
    "m_same_calc": 'CALCULATE([Sales], ALLSELECTED(T[Cat]), T[Cat] = "A")',
    "t_tab_cat": 'CALCULATE(COUNTROWS(ALLSELECTED(T)), T[Cat] = "A")',
    "t_col_same": 'CALCULATE(COUNTROWS(ALLSELECTED(T[Cat])), T[Cat] = "A")',
    "t_col_other": 'CALCULATE(COUNTROWS(ALLSELECTED(T[Region])), T[Cat] = "A")',
    "t_dim_tab": 'CALCULATE(COUNTROWS(ALLSELECTED(D)), D[Zone] = "Z1")',
    "t_region_same": 'CALCULATE(COUNTROWS(ALLSELECTED(T[Region])), T[Region] = "North")',
    "t_noarg_sum": 'CALCULATE(SUMX(ALLSELECTED(T), T[Amount]), T[Cat] = "A")',
    "s_cat_tab": "SUMX(VALUES(T[Cat]), CALCULATE(COUNTROWS(ALLSELECTED(T))))",
    "s_cat_col": "SUMX(VALUES(T[Cat]), CALCULATE(COUNTROWS(ALLSELECTED(T[Cat]))))",
    "s_cat_mod": "SUMX(VALUES(T[Cat]), CALCULATE([Sales], ALLSELECTED(T[Cat])))",
    "s_in_calc": 'CALCULATE(SUMX(VALUES(T[Cat]), CALCULATE(COUNTROWS(ALLSELECTED(T)))), T[Region] = "North")',
    "s_filter_all": 'SUMX(FILTER(ALL(T[Cat]), T[Cat] = "A"), CALCULATE(COUNTROWS(ALLSELECTED(T))))',
    "s_rows": "SUMX(T, CALCULATE(COUNTROWS(ALLSELECTED(T))))",
    "s_rows_mod": "SUMX(T, CALCULATE([Sales], ALLSELECTED(T)))",
    "d_max_prev": "CALCULATE(MAXX(FILTER(ALLSELECTED(Dt), NOT ISBLANK([FS])), Dt[Month]), "
                  "DATEADD(Dt[Date], -1, MONTH))",
    "d_rows_prev": "CALCULATE(COUNTROWS(ALLSELECTED(Dt)), DATEADD(Dt[Date], -1, MONTH))",
    "d_col_month": "CALCULATE(COUNTROWS(ALLSELECTED(Dt[Date])), Dt[Month] = 2)",
    "d_sum_prev": "CALCULATE(SUMX(ALLSELECTED(Dt), [FS]), DATEADD(Dt[Date], -1, MONTH))",
    "f_inscope_rows": "COUNTROWS(FILTER(T, CALCULATE(IF(ISINSCOPE(T[Cat]), 1, 0)) = 1))",
    "f_inscope_vals": "COUNTROWS(FILTER(VALUES(T[Cat]), CALCULATE(IF(ISINSCOPE(T[Cat]), 1, 0)) = 1))",
    "f_rows_allsel": "SUMX(FILTER(T, CALCULATE(COUNTROWS(ALLSELECTED(T))) = 4), 1)",
}
SHAPES = {   # shape -> (grouping key, slicer filter)
    "total": (None, {}), "by_zone": ("D.Zone", {}), "by_cat": ("T.Cat", {}), "by_month": ("Dt.Month", {}),
    "slicer_tregion_n": (None, {"T.Region": ["North"]}), "slicer_zone_z1": (None, {"D.Zone": ["Z1"]}),
    "slicer_cat_b": (None, {"T.Cat": ["B"]}), "slicer_month_3": (None, {"Dt.Month": [3]}),
    "by_cat_tregion_n": ("T.Cat", {"T.Region": ["North"]}), "by_month_month_3": ("Dt.Month", {"Dt.Month": [3]}),
}

DESKTOP = [   # (shape, group value, measure, Power BI Desktop 2.152) -- generated
    ('total', None, 'm_tab_cat', 40),
    ('total', None, 'm_col_same', 40),
    ('total', None, 'm_col_other', 40),
    ('total', None, 'm_noarg', 40),
    ('total', None, 'm_dim_tab', 30),
    ('total', None, 'm_dim_col', 30),
    ('total', None, 'm_same_calc', 40),
    ('total', None, 't_tab_cat', 2),
    ('total', None, 't_col_same', 1),
    ('total', None, 't_col_other', 2),
    ('total', None, 't_dim_tab', 1),
    ('total', None, 't_region_same', 1),
    ('total', None, 't_noarg_sum', 40),
    ('total', None, 's_cat_tab', 8),
    ('total', None, 's_cat_col', 4),
    ('total', None, 's_cat_mod', 150),
    ('total', None, 's_in_calc', 4),
    ('total', None, 's_filter_all', 2),
    ('total', None, 's_rows', 16),
    ('total', None, 's_rows_mod', 300),
    ('total', None, 'd_max_prev', 2),
    ('total', None, 'd_rows_prev', 60),
    ('total', None, 'd_col_month', 91),
    ('total', None, 'd_sum_prev', 234),
    ('total', None, 'f_inscope_rows', 4),
    ('total', None, 'f_inscope_vals', 2),
    ('total', None, 'f_rows_allsel', 4),
    ('by_zone', 'Z1', 'm_tab_cat', 40),
    ('by_zone', 'Z2', 'm_tab_cat', 40),
    ('by_zone', 'Z1', 'm_col_same', 10),
    ('by_zone', 'Z2', 'm_col_same', 30),
    ('by_zone', 'Z1', 'm_col_other', 10),
    ('by_zone', 'Z2', 'm_col_other', 30),
    ('by_zone', 'Z1', 'm_noarg', 40),
    ('by_zone', 'Z2', 'm_noarg', 40),
    ('by_zone', 'Z1', 'm_dim_tab', 30),
    ('by_zone', 'Z2', 'm_dim_tab', 30),
    ('by_zone', 'Z1', 'm_dim_col', 30),
    ('by_zone', 'Z2', 'm_dim_col', 30),
    ('by_zone', 'Z1', 'm_same_calc', 10),
    ('by_zone', 'Z2', 'm_same_calc', 30),
    ('by_zone', 'Z1', 't_tab_cat', 2),
    ('by_zone', 'Z2', 't_tab_cat', 2),
    ('by_zone', 'Z1', 't_col_same', 1),
    ('by_zone', 'Z2', 't_col_same', 1),
    ('by_zone', 'Z1', 't_col_other', 2),
    ('by_zone', 'Z2', 't_col_other', 2),
    ('by_zone', 'Z1', 't_dim_tab', 1),
    ('by_zone', 'Z2', 't_dim_tab', 1),
    ('by_zone', 'Z1', 't_region_same', 1),
    ('by_zone', 'Z2', 't_region_same', 1),
    ('by_zone', 'Z1', 't_noarg_sum', 40),
    ('by_zone', 'Z2', 't_noarg_sum', 40),
    ('by_zone', 'Z1', 's_cat_tab', 8),
    ('by_zone', 'Z2', 's_cat_tab', 8),
    ('by_zone', 'Z1', 's_cat_col', 4),
    ('by_zone', 'Z2', 's_cat_col', 4),
    ('by_zone', 'Z1', 's_cat_mod', 60),
    ('by_zone', 'Z2', 's_cat_mod', 90),
    ('by_zone', 'Z1', 's_in_calc', 4),
    ('by_zone', 'Z2', 's_in_calc', None),
    ('by_zone', 'Z1', 's_filter_all', 2),
    ('by_zone', 'Z2', 's_filter_all', 2),
    ('by_zone', 'Z1', 's_rows', 4),
    ('by_zone', 'Z2', 's_rows', 4),
    ('by_zone', 'Z1', 's_rows_mod', 60),
    ('by_zone', 'Z2', 's_rows_mod', 90),
    ('by_zone', 'Z1', 'd_max_prev', 2),
    ('by_zone', 'Z2', 'd_max_prev', 2),
    ('by_zone', 'Z1', 'd_rows_prev', 60),
    ('by_zone', 'Z2', 'd_rows_prev', 60),
    ('by_zone', 'Z1', 'd_col_month', 91),
    ('by_zone', 'Z2', 'd_col_month', 91),
    ('by_zone', 'Z1', 'd_sum_prev', 234),
    ('by_zone', 'Z2', 'd_sum_prev', 234),
    ('by_zone', 'Z1', 'f_inscope_rows', 2),
    ('by_zone', 'Z2', 'f_inscope_rows', 2),
    ('by_zone', 'Z1', 'f_inscope_vals', 2),
    ('by_zone', 'Z2', 'f_inscope_vals', 2),
    ('by_zone', 'Z1', 'f_rows_allsel', None),
    ('by_zone', 'Z2', 'f_rows_allsel', None),
    ('by_cat', 'A', 'm_tab_cat', 40),
    ('by_cat', 'B', 'm_tab_cat', 40),
    ('by_cat', 'A', 'm_col_same', 40),
    ('by_cat', 'B', 'm_col_same', 40),
    ('by_cat', 'A', 'm_col_other', 40),
    ('by_cat', 'B', 'm_col_other', 40),
    ('by_cat', 'A', 'm_noarg', 40),
    ('by_cat', 'B', 'm_noarg', 40),
    ('by_cat', 'A', 'm_dim_tab', 10),
    ('by_cat', 'B', 'm_dim_tab', 20),
    ('by_cat', 'A', 'm_dim_col', 10),
    ('by_cat', 'B', 'm_dim_col', 20),
    ('by_cat', 'A', 'm_same_calc', 40),
    ('by_cat', 'B', 'm_same_calc', 40),
    ('by_cat', 'A', 't_tab_cat', 2),
    ('by_cat', 'B', 't_tab_cat', 2),
    ('by_cat', 'A', 't_col_same', 1),
    ('by_cat', 'B', 't_col_same', 1),
    ('by_cat', 'A', 't_col_other', 2),
    ('by_cat', 'B', 't_col_other', 2),
    ('by_cat', 'A', 't_dim_tab', 1),
    ('by_cat', 'B', 't_dim_tab', 1),
    ('by_cat', 'A', 't_region_same', 1),
    ('by_cat', 'B', 't_region_same', 1),
    ('by_cat', 'A', 't_noarg_sum', 40),
    ('by_cat', 'B', 't_noarg_sum', 40),
    ('by_cat', 'A', 's_cat_tab', 2),
    ('by_cat', 'B', 's_cat_tab', 2),
    ('by_cat', 'A', 's_cat_col', 1),
    ('by_cat', 'B', 's_cat_col', 1),
    ('by_cat', 'A', 's_cat_mod', 40),
    ('by_cat', 'B', 's_cat_mod', 35),
    ('by_cat', 'A', 's_in_calc', 1),
    ('by_cat', 'B', 's_in_calc', 1),
    ('by_cat', 'A', 's_filter_all', 2),
    ('by_cat', 'B', 's_filter_all', 2),
    ('by_cat', 'A', 's_rows', 4),
    ('by_cat', 'B', 's_rows', 4),
    ('by_cat', 'A', 's_rows_mod', 80),
    ('by_cat', 'B', 's_rows_mod', 70),
    ('by_cat', 'A', 'd_max_prev', 2),
    ('by_cat', 'B', 'd_max_prev', 2),
    ('by_cat', 'A', 'd_rows_prev', 60),
    ('by_cat', 'B', 'd_rows_prev', 60),
    ('by_cat', 'A', 'd_col_month', 91),
    ('by_cat', 'B', 'd_col_month', 91),
    ('by_cat', 'A', 'd_sum_prev', 234),
    ('by_cat', 'B', 'd_sum_prev', 234),
    ('by_cat', 'A', 'f_inscope_rows', 2),
    ('by_cat', 'B', 'f_inscope_rows', 2),
    ('by_cat', 'A', 'f_inscope_vals', 1),
    ('by_cat', 'B', 'f_inscope_vals', 1),
    ('by_cat', 'A', 'f_rows_allsel', None),
    ('by_cat', 'B', 'f_rows_allsel', None),
    ('by_month', 1, 'm_tab_cat', 40),
    ('by_month', 2, 'm_tab_cat', 40),
    ('by_month', 3, 'm_tab_cat', 40),
    ('by_month', 1, 'm_col_same', 40),
    ('by_month', 2, 'm_col_same', 40),
    ('by_month', 3, 'm_col_same', 40),
    ('by_month', 1, 'm_col_other', 40),
    ('by_month', 2, 'm_col_other', 40),
    ('by_month', 3, 'm_col_other', 40),
    ('by_month', 1, 'm_noarg', 40),
    ('by_month', 2, 'm_noarg', 40),
    ('by_month', 3, 'm_noarg', 40),
    ('by_month', 1, 'm_dim_tab', 30),
    ('by_month', 2, 'm_dim_tab', 30),
    ('by_month', 3, 'm_dim_tab', 30),
    ('by_month', 1, 'm_dim_col', 30),
    ('by_month', 2, 'm_dim_col', 30),
    ('by_month', 3, 'm_dim_col', 30),
    ('by_month', 1, 'm_same_calc', 40),
    ('by_month', 2, 'm_same_calc', 40),
    ('by_month', 3, 'm_same_calc', 40),
    ('by_month', 1, 't_tab_cat', 2),
    ('by_month', 2, 't_tab_cat', 2),
    ('by_month', 3, 't_tab_cat', 2),
    ('by_month', 1, 't_col_same', 1),
    ('by_month', 2, 't_col_same', 1),
    ('by_month', 3, 't_col_same', 1),
    ('by_month', 1, 't_col_other', 2),
    ('by_month', 2, 't_col_other', 2),
    ('by_month', 3, 't_col_other', 2),
    ('by_month', 1, 't_dim_tab', 1),
    ('by_month', 2, 't_dim_tab', 1),
    ('by_month', 3, 't_dim_tab', 1),
    ('by_month', 1, 't_region_same', 1),
    ('by_month', 2, 't_region_same', 1),
    ('by_month', 3, 't_region_same', 1),
    ('by_month', 1, 't_noarg_sum', 40),
    ('by_month', 2, 't_noarg_sum', 40),
    ('by_month', 3, 't_noarg_sum', 40),
    ('by_month', 1, 's_cat_tab', 8),
    ('by_month', 2, 's_cat_tab', 8),
    ('by_month', 3, 's_cat_tab', 8),
    ('by_month', 1, 's_cat_col', 4),
    ('by_month', 2, 's_cat_col', 4),
    ('by_month', 3, 's_cat_col', 4),
    ('by_month', 1, 's_cat_mod', 150),
    ('by_month', 2, 's_cat_mod', 150),
    ('by_month', 3, 's_cat_mod', 150),
    ('by_month', 1, 's_in_calc', 4),
    ('by_month', 2, 's_in_calc', 4),
    ('by_month', 3, 's_in_calc', 4),
    ('by_month', 1, 's_filter_all', 2),
    ('by_month', 2, 's_filter_all', 2),
    ('by_month', 3, 's_filter_all', 2),
    ('by_month', 1, 's_rows', 16),
    ('by_month', 2, 's_rows', 16),
    ('by_month', 3, 's_rows', 16),
    ('by_month', 1, 's_rows_mod', 300),
    ('by_month', 2, 's_rows_mod', 300),
    ('by_month', 3, 's_rows_mod', 300),
    ('by_month', 1, 'd_max_prev', None),
    ('by_month', 2, 'd_max_prev', 1),
    ('by_month', 3, 'd_max_prev', 2),
    ('by_month', 1, 'd_rows_prev', None),
    ('by_month', 2, 'd_rows_prev', 31),
    ('by_month', 3, 'd_rows_prev', 29),
    ('by_month', 1, 'd_col_month', 91),
    ('by_month', 2, 'd_col_month', 91),
    ('by_month', 3, 'd_col_month', 91),
    ('by_month', 1, 'd_sum_prev', None),
    ('by_month', 2, 'd_sum_prev', 118),
    ('by_month', 3, 'd_sum_prev', 116),
    ('by_month', 1, 'f_inscope_rows', 4),
    ('by_month', 2, 'f_inscope_rows', 4),
    ('by_month', 3, 'f_inscope_rows', 4),
    ('by_month', 1, 'f_inscope_vals', 2),
    ('by_month', 2, 'f_inscope_vals', 2),
    ('by_month', 3, 'f_inscope_vals', 2),
    ('by_month', 1, 'f_rows_allsel', 4),
    ('by_month', 2, 'f_rows_allsel', 4),
    ('by_month', 3, 'f_rows_allsel', 4),
    ('slicer_tregion_n', None, 'm_tab_cat', 10),
    ('slicer_tregion_n', None, 'm_col_same', 10),
    ('slicer_tregion_n', None, 'm_col_other', 10),
    ('slicer_tregion_n', None, 'm_noarg', 10),
    ('slicer_tregion_n', None, 'm_dim_tab', 30),
    ('slicer_tregion_n', None, 'm_dim_col', 30),
    ('slicer_tregion_n', None, 'm_same_calc', 10),
    ('slicer_tregion_n', None, 't_tab_cat', 1),
    ('slicer_tregion_n', None, 't_col_same', 1),
    ('slicer_tregion_n', None, 't_col_other', 1),
    ('slicer_tregion_n', None, 't_dim_tab', 1),
    ('slicer_tregion_n', None, 't_region_same', 1),
    ('slicer_tregion_n', None, 't_noarg_sum', 10),
    ('slicer_tregion_n', None, 's_cat_tab', 4),
    ('slicer_tregion_n', None, 's_cat_col', 4),
    ('slicer_tregion_n', None, 's_cat_mod', 60),
    ('slicer_tregion_n', None, 's_in_calc', 4),
    ('slicer_tregion_n', None, 's_filter_all', 1),
    ('slicer_tregion_n', None, 's_rows', 4),
    ('slicer_tregion_n', None, 's_rows_mod', 60),
    ('slicer_tregion_n', None, 'd_max_prev', 2),
    ('slicer_tregion_n', None, 'd_rows_prev', 60),
    ('slicer_tregion_n', None, 'd_col_month', 91),
    ('slicer_tregion_n', None, 'd_sum_prev', 234),
    ('slicer_tregion_n', None, 'f_inscope_rows', 2),
    ('slicer_tregion_n', None, 'f_inscope_vals', 2),
    ('slicer_tregion_n', None, 'f_rows_allsel', None),
    ('slicer_zone_z1', None, 'm_tab_cat', 10),
    ('slicer_zone_z1', None, 'm_col_same', 10),
    ('slicer_zone_z1', None, 'm_col_other', 10),
    ('slicer_zone_z1', None, 'm_noarg', 10),
    ('slicer_zone_z1', None, 'm_dim_tab', 30),
    ('slicer_zone_z1', None, 'm_dim_col', 30),
    ('slicer_zone_z1', None, 'm_same_calc', 10),
    ('slicer_zone_z1', None, 't_tab_cat', 1),
    ('slicer_zone_z1', None, 't_col_same', 1),
    ('slicer_zone_z1', None, 't_col_other', 2),
    ('slicer_zone_z1', None, 't_dim_tab', 1),
    ('slicer_zone_z1', None, 't_region_same', 1),
    ('slicer_zone_z1', None, 't_noarg_sum', 10),
    ('slicer_zone_z1', None, 's_cat_tab', 4),
    ('slicer_zone_z1', None, 's_cat_col', 4),
    ('slicer_zone_z1', None, 's_cat_mod', 60),
    ('slicer_zone_z1', None, 's_in_calc', 4),
    ('slicer_zone_z1', None, 's_filter_all', 1),
    ('slicer_zone_z1', None, 's_rows', 4),
    ('slicer_zone_z1', None, 's_rows_mod', 60),
    ('slicer_zone_z1', None, 'd_max_prev', 2),
    ('slicer_zone_z1', None, 'd_rows_prev', 60),
    ('slicer_zone_z1', None, 'd_col_month', 91),
    ('slicer_zone_z1', None, 'd_sum_prev', 234),
    ('slicer_zone_z1', None, 'f_inscope_rows', 2),
    ('slicer_zone_z1', None, 'f_inscope_vals', 2),
    ('slicer_zone_z1', None, 'f_rows_allsel', None),
    ('slicer_cat_b', None, 'm_tab_cat', 40),
    ('slicer_cat_b', None, 'm_col_same', 40),
    ('slicer_cat_b', None, 'm_col_other', 40),
    ('slicer_cat_b', None, 'm_noarg', 40),
    ('slicer_cat_b', None, 'm_dim_tab', 20),
    ('slicer_cat_b', None, 'm_dim_col', 20),
    ('slicer_cat_b', None, 'm_same_calc', 40),
    ('slicer_cat_b', None, 't_tab_cat', 2),
    ('slicer_cat_b', None, 't_col_same', 1),
    ('slicer_cat_b', None, 't_col_other', 2),
    ('slicer_cat_b', None, 't_dim_tab', 1),
    ('slicer_cat_b', None, 't_region_same', 1),
    ('slicer_cat_b', None, 't_noarg_sum', 40),
    ('slicer_cat_b', None, 's_cat_tab', 2),
    ('slicer_cat_b', None, 's_cat_col', 1),
    ('slicer_cat_b', None, 's_cat_mod', 35),
    ('slicer_cat_b', None, 's_in_calc', 1),
    ('slicer_cat_b', None, 's_filter_all', 2),
    ('slicer_cat_b', None, 's_rows', 4),
    ('slicer_cat_b', None, 's_rows_mod', 70),
    ('slicer_cat_b', None, 'd_max_prev', 2),
    ('slicer_cat_b', None, 'd_rows_prev', 60),
    ('slicer_cat_b', None, 'd_col_month', 91),
    ('slicer_cat_b', None, 'd_sum_prev', 234),
    ('slicer_cat_b', None, 'f_inscope_rows', 2),
    ('slicer_cat_b', None, 'f_inscope_vals', 1),
    ('slicer_cat_b', None, 'f_rows_allsel', None),
    ('slicer_month_3', None, 'm_tab_cat', 40),
    ('slicer_month_3', None, 'm_col_same', 40),
    ('slicer_month_3', None, 'm_col_other', 40),
    ('slicer_month_3', None, 'm_noarg', 40),
    ('slicer_month_3', None, 'm_dim_tab', 30),
    ('slicer_month_3', None, 'm_dim_col', 30),
    ('slicer_month_3', None, 'm_same_calc', 40),
    ('slicer_month_3', None, 't_tab_cat', 2),
    ('slicer_month_3', None, 't_col_same', 1),
    ('slicer_month_3', None, 't_col_other', 2),
    ('slicer_month_3', None, 't_dim_tab', 1),
    ('slicer_month_3', None, 't_region_same', 1),
    ('slicer_month_3', None, 't_noarg_sum', 40),
    ('slicer_month_3', None, 's_cat_tab', 8),
    ('slicer_month_3', None, 's_cat_col', 4),
    ('slicer_month_3', None, 's_cat_mod', 150),
    ('slicer_month_3', None, 's_in_calc', 4),
    ('slicer_month_3', None, 's_filter_all', 2),
    ('slicer_month_3', None, 's_rows', 16),
    ('slicer_month_3', None, 's_rows_mod', 300),
    ('slicer_month_3', None, 'd_max_prev', None),
    ('slicer_month_3', None, 'd_rows_prev', None),
    ('slicer_month_3', None, 'd_col_month', 91),
    ('slicer_month_3', None, 'd_sum_prev', None),
    ('slicer_month_3', None, 'f_inscope_rows', 4),
    ('slicer_month_3', None, 'f_inscope_vals', 2),
    ('slicer_month_3', None, 'f_rows_allsel', 4),
    ('by_cat_tregion_n', 'A', 'm_tab_cat', 10),
    ('by_cat_tregion_n', 'B', 'm_tab_cat', 10),
    ('by_cat_tregion_n', 'A', 'm_col_same', 10),
    ('by_cat_tregion_n', 'B', 'm_col_same', 10),
    ('by_cat_tregion_n', 'A', 'm_col_other', 10),
    ('by_cat_tregion_n', 'B', 'm_col_other', 10),
    ('by_cat_tregion_n', 'A', 'm_noarg', 10),
    ('by_cat_tregion_n', 'B', 'm_noarg', 10),
    ('by_cat_tregion_n', 'A', 'm_dim_tab', 10),
    ('by_cat_tregion_n', 'B', 'm_dim_tab', 20),
    ('by_cat_tregion_n', 'A', 'm_dim_col', 10),
    ('by_cat_tregion_n', 'B', 'm_dim_col', 20),
    ('by_cat_tregion_n', 'A', 'm_same_calc', 10),
    ('by_cat_tregion_n', 'B', 'm_same_calc', 10),
    ('by_cat_tregion_n', 'A', 't_tab_cat', 1),
    ('by_cat_tregion_n', 'B', 't_tab_cat', 1),
    ('by_cat_tregion_n', 'A', 't_col_same', 1),
    ('by_cat_tregion_n', 'B', 't_col_same', 1),
    ('by_cat_tregion_n', 'A', 't_col_other', 1),
    ('by_cat_tregion_n', 'B', 't_col_other', 1),
    ('by_cat_tregion_n', 'A', 't_dim_tab', 1),
    ('by_cat_tregion_n', 'B', 't_dim_tab', 1),
    ('by_cat_tregion_n', 'A', 't_region_same', 1),
    ('by_cat_tregion_n', 'B', 't_region_same', 1),
    ('by_cat_tregion_n', 'A', 't_noarg_sum', 10),
    ('by_cat_tregion_n', 'B', 't_noarg_sum', 10),
    ('by_cat_tregion_n', 'A', 's_cat_tab', 1),
    ('by_cat_tregion_n', 'B', 's_cat_tab', 1),
    ('by_cat_tregion_n', 'A', 's_cat_col', 1),
    ('by_cat_tregion_n', 'B', 's_cat_col', 1),
    ('by_cat_tregion_n', 'A', 's_cat_mod', 10),
    ('by_cat_tregion_n', 'B', 's_cat_mod', 20),
    ('by_cat_tregion_n', 'A', 's_in_calc', 1),
    ('by_cat_tregion_n', 'B', 's_in_calc', 1),
    ('by_cat_tregion_n', 'A', 's_filter_all', 1),
    ('by_cat_tregion_n', 'B', 's_filter_all', 1),
    ('by_cat_tregion_n', 'A', 's_rows', 1),
    ('by_cat_tregion_n', 'B', 's_rows', 1),
    ('by_cat_tregion_n', 'A', 's_rows_mod', 10),
    ('by_cat_tregion_n', 'B', 's_rows_mod', 20),
    ('by_cat_tregion_n', 'A', 'd_max_prev', 2),
    ('by_cat_tregion_n', 'B', 'd_max_prev', 2),
    ('by_cat_tregion_n', 'A', 'd_rows_prev', 60),
    ('by_cat_tregion_n', 'B', 'd_rows_prev', 60),
    ('by_cat_tregion_n', 'A', 'd_col_month', 91),
    ('by_cat_tregion_n', 'B', 'd_col_month', 91),
    ('by_cat_tregion_n', 'A', 'd_sum_prev', 234),
    ('by_cat_tregion_n', 'B', 'd_sum_prev', 234),
    ('by_cat_tregion_n', 'A', 'f_inscope_rows', 1),
    ('by_cat_tregion_n', 'B', 'f_inscope_rows', 1),
    ('by_cat_tregion_n', 'A', 'f_inscope_vals', 1),
    ('by_cat_tregion_n', 'B', 'f_inscope_vals', 1),
    ('by_cat_tregion_n', 'A', 'f_rows_allsel', None),
    ('by_cat_tregion_n', 'B', 'f_rows_allsel', None),
    ('by_month_month_3', 3, 'm_tab_cat', 40),
    ('by_month_month_3', 3, 'm_col_same', 40),
    ('by_month_month_3', 3, 'm_col_other', 40),
    ('by_month_month_3', 3, 'm_noarg', 40),
    ('by_month_month_3', 3, 'm_dim_tab', 30),
    ('by_month_month_3', 3, 'm_dim_col', 30),
    ('by_month_month_3', 3, 'm_same_calc', 40),
    ('by_month_month_3', 3, 't_tab_cat', 2),
    ('by_month_month_3', 3, 't_col_same', 1),
    ('by_month_month_3', 3, 't_col_other', 2),
    ('by_month_month_3', 3, 't_dim_tab', 1),
    ('by_month_month_3', 3, 't_region_same', 1),
    ('by_month_month_3', 3, 't_noarg_sum', 40),
    ('by_month_month_3', 3, 's_cat_tab', 8),
    ('by_month_month_3', 3, 's_cat_col', 4),
    ('by_month_month_3', 3, 's_cat_mod', 150),
    ('by_month_month_3', 3, 's_in_calc', 4),
    ('by_month_month_3', 3, 's_filter_all', 2),
    ('by_month_month_3', 3, 's_rows', 16),
    ('by_month_month_3', 3, 's_rows_mod', 300),
    ('by_month_month_3', 3, 'd_max_prev', None),
    ('by_month_month_3', 3, 'd_rows_prev', None),
    ('by_month_month_3', 3, 'd_col_month', 91),
    ('by_month_month_3', 3, 'd_sum_prev', None),
    ('by_month_month_3', 3, 'f_inscope_rows', 4),
    ('by_month_month_3', 3, 'f_inscope_vals', 2),
    ('by_month_month_3', 3, 'f_rows_allsel', 4),
]


@pytest.mark.parametrize("shape,group,measure,want", DESKTOP,
                         ids=[f"{s}|{g}|{m}" for s, g, m, _w in DESKTOP])
def test_matches_desktop(shape, group, measure, want):
    grp, slicer = SHAPES[shape]
    fc = dict(slicer)
    kw = {}
    if grp:
        fc[grp] = [group]
        kw = dict(group_by={grp}, selected_filters=dict(slicer))
    got = de.evaluate_measures_smart([measure], TABLES, MEASURES, fc, relationships=RELS,
                                     simulate_row_context=False, **kw)[measure]
    if want is None:
        assert got is None
    else:
        assert got == pytest.approx(want)


# ---- build_b137.py: ALLSELECTED's restore is no new date filter -------------
# A filter on a DateTime column that joins a relationship clears its table's
# other filters (#78). What ALLSELECTED puts back on that column does not:
# Desktop 2.152 keeps the row's month in
# MINX(D, CALCULATE(CALCULATE(COUNTROWS(D), ALLSELECTED(D[Date])))) -- 29, the
# shortest month -- and an explicit date filter still clears it (1, and
# ISFILTERED(D[Month]) FALSE).
D_DAYS = [datetime(2024, 1, 1) + timedelta(days=i) for i in range(91)]
D_TABLES = {
    "D": {"columns": ["Date", "Month"], "rows": [[d, d.month] for d in D_DAYS]},
    "G": {"columns": ["Date", "Amount"],
          "rows": [[d, float(i + 1) / 2] for i, d in enumerate(D_DAYS[::3]) for _half in (0, 1)]},
}
D_RELS = [{"FromTable": "G", "FromColumn": "Date", "ToTable": "D", "ToColumn": "Date", "IsActive": True,
           "CrossFilteringBehavior": 1, "FromCardinality": 2, "ToCardinality": 1}]
D_PROBES = {   # Power BI Desktop 2.152, unmarked and marked calendars alike
    "MINX(D, CALCULATE(CALCULATE(COUNTROWS(D), ALLSELECTED(D[Date]))))": 29,
    "MINX(D, CALCULATE(CALCULATE(IF(ISFILTERED(D[Month]), 1, 0), ALLSELECTED(D[Date]))))": 1,
    "MINX(D, CALCULATE(CALCULATE(COUNTROWS(D), D[Date] = DATE(2024, 3, 1))))": 1,
    "MINX(D, CALCULATE(CALCULATE(IF(ISFILTERED(D[Month]), 1, 0), D[Date] = DATE(2024, 3, 1))))": 0,
}


@pytest.mark.parametrize("expr", list(D_PROBES))
def test_allselected_restore_is_no_date_filter(expr):
    got = de.evaluate_measures_batch(["p"], D_TABLES, {"p": expr}, {}, relationships=D_RELS)["p"]
    assert got == D_PROBES[expr]
